### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by Mitra-M** [PJayB/DirectCompositionDirectX12Sample#1]
Hi,

I can't compile the project, (Tested on 2 win10 machine with full update+DX11+latest Win10 SDK)
I got these errors:
Severity    Code    Description Project File    Line    Suppression State
Error (active)      more than one instance of overloaded function "StgCreateStorageEx" has 'C' linkage  DirectCompositeSample   c:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\um\coml2api.h   191 
Error (active)      more than one instance of overloaded function "StgOpenStorageEx" has 'C' linkage    DirectCompositeSample   c:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\um\coml2api.h   205 
Error (active)      more than one instance of overloaded function "IEnumSTATPROPSTG_Next_Proxy" has 'C' linkage DirectCompositeSample   c:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\um\PropIdlBase.h    1125  
Error (active)      more than one instance of overloaded function "IEnumSTATPROPSTG_Next_Stub" has 'C' linkage  DirectCompositeSample   c:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\um\PropIdlBase.h    1134  
Error (active)      more than one instance of overloaded function "IEnumSTATPROPSETSTG_Next_Proxy" has 'C' linkage  DirectCompositeSample   c:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\um\PropIdlBase.h    1140  
Error (active)      more than one instance of overloaded function "IEnumSTATPROPSETSTG_Next_Stub" has 'C' linkage   DirectCompositeSample   c:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\um\PropIdlBase.h    1149  
Error   C2011   'tagVersionedStream': 'struct' type redefinition    DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    107 
Error   C2011   'tagCAC': 'struct' type redefinition    DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    141 
Error   C2011   'tagCAUB': 'struct' type redefinition   DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    147 
Error   C2011   'tagCAI': 'struct' type redefinition    DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    153 
Error   C2011   'tagCAUI': 'struct' type redefinition   DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    159 
Error   C2011   'tagCAL': 'struct' type redefinition    DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    165 
Error   C2011   'tagCAUL': 'struct' type redefinition   DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    171 
Error   C2011   'tagCAFLT': 'struct' type redefinition  DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    177 
Error   C2011   'tagCADBL': 'struct' type redefinition  DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    183 
Error   C2011   'tagCACY': 'struct' type redefinition   DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    189 
Error   C2011   'tagCADATE': 'struct' type redefinition DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    195 
Error   C2011   'tagCABSTR': 'struct' type redefinition DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    201 
Error   C2011   'tagCABSTRBLOB': 'struct' type redefinition DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    207 
Error   C2011   'tagCABOOL': 'struct' type redefinition DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    213 
Error   C2011   'tagCASCODE': 'struct' type redefinition    DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    219 
Error   C2011   'tagCAPROPVARIANT': 'struct' type redefinition  DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    225 
Error   C2011   'tagCAH': 'struct' type redefinition    DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    231 
Error   C2011   'tagCAUH': 'struct' type redefinition   DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    237 
Error   C2011   'tagCALPSTR': 'struct' type redefinition    DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    243 
Error   C2011   'tagCALPWSTR': 'struct' type redefinition   DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    249 
Error   C2011   'tagCAFILETIME': 'struct' type redefinition DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    255 
Error   C2011   'tagCACLIPDATA': 'struct' type redefinition DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    261 
Error   C2011   'tagCACLSID': 'struct' type redefinition    DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    267 
Error   C2011   'tagPROPVARIANT': 'struct' type redefinition    DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    294 
Error   C2011   'tagPROPSPEC': 'struct' type redefinition   DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    442 
Error   C2011   'tagSTATPROPSTG': 'struct' type redefinition    DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    453 
Error   C2011   'tagSTATPROPSETSTG': 'struct' type redefinition DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\propidlbase.h    465 
Error   C2011   'tagSTGOPTIONS': 'struct' type redefinition DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\coml2api.h   179 
Error   C2061   syntax error: identifier 'DXGI_COLOR_SPACE_TYPE'    DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\shared\dxgi1_4.h    115 
Error   C2061   syntax error: identifier 'DXGI_COLOR_SPACE_TYPE'    DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\shared\dxgi1_4.h    121 
Error   C2061   syntax error: identifier 'DXGI_COLOR_SPACE_TYPE'    DirectCompositeSample   c:\program files (x86)\windows kits\10\include\10.0.10586.0\shared\dxgi1_4.h    562 
Error   C2011   '_D3D_PARAMETER_FLAGS': 'enum' type redefinition    DirectCompositeSample   c:\program files (x86)\windows kits\8.1\include\um\d3d11shader.h    42

**Comment by PeteLewisATG** [comment]
Hmm, that's weird. On all the machines I test this on it builds fine under both 10.10240 and 10.10586 SDKs. What is the value for Target Platform Version in the Project Properties?

**Comment by PJayB** [comment]
Hmm, that's weird. On all the machines I test this on it builds fine under both 10.10240 and 10.10586 SDKs. What is the value for Target Platform Version in the Project Properties? Which SDKs do you have installed?

**Comment by Mitra-M** [comment]
Thank you , the Target Platform Version was wrong, I set it to 10.0.10586.0 then compiled.
Now I can compile the project without any problem,  but I can not run it .
I got an error in the DirectCompositeSample.cpp file at this line:
ThrowIfFailed(m_device->CreateCommandQueue(&queueDesc, IID_PPV_ARGS(&m_commandQueue))); 

Please see [this ](https://drive.google.com/file/d/0B7xJ3vpXXdvQd1JDajh0c1FfTFk/view?usp=sharing)and  [this](https://drive.google.com/file/d/0B7xJ3vpXXdvQMjlkUmlFR2JpcFU/view?usp=sharing) images.

**Comment by PJayB** [comment]
I'd appreciate it if you could debug that further as I can't do that from screenshots. Check your Output window for validation errors.

**Comment by Mitra-M** [comment]
with change 
`if (m_useWarpDevice)`
 to 
`if (!m_useWarpDevice)` 
 the problem solved.

I expected to get less than 1% of CPU usage while it is about 4%.
but anyway ,it is a very good sample for me, Thank you for share it. 

My knowledge about the DirectX is low, would you reply to my bellow question please?
Can we capture an off screen window using DXGI?

Best regards
Mitra

**Comment by PJayB** [comment]
What you have done there is enable the WARP device. That means you are emulating the GPU in software, and that is why you see higher than expected CPU usage. If you are unable to run without WARP make sure you have a DirectX 12 compatible video card.

Your other question would be better asked on StackOverflow, social.msdn.com or other support site.

**Comment by Mitra-M** [comment]
Thank you.
